### ISSUE TITLE
Can a linux binary be released through github releases? 

### ISSUE THREAD

**Issue by mohsen0** [grapeshot/vault_exporter#1]
I am not sure if that could be contributed to the exporter.
But let me know if that would be something doable

**Comment by tomwilkie** [comment]
Sure I don't see why not!  I'll take a look at getting this working tomorrow.

**Comment by mohsen0** [comment]
Thank you!

**Comment by anitakrueger** [comment]
A release would be awesome. Anything I can do to help?

**Comment by apenney** [comment]
Any news on this one @tomwilkie - we're looking to use this but we're having to cram a go build process into our ansible playbooks which made me a little sad :)

**Comment by tomwilkie** [comment]
Here you go: https://github.com/grapeshot/vault_exporter/releases/tag/v0.1.0

Sorry for the delay.
