### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by tomwilkie** [grapeshot/vault_exporter#3]
Ideally automatically publishing to the docker hub.  @jdbaldry do you have admin rights on this org?

**Comment by tomwilkie** [comment]
Mind setting up circle ci?  If you enable it I'll do the rest of the work.

**Comment by dastergon** [comment]
Any updates on this? Would be great to also  publish releases on Github

**Comment by jdbaldry** [comment]
Sorry for the delay on this! 

We have CI in place now that will automate releases for us and also push the images to Docker Hub https://hub.docker.com/r/grapeshot/vault_exporter/
