### ISSUE TITLE
Possible to expose a `vault_build_info` metric?

### ISSUE THREAD

**Issue by hairyhenderson** [grapeshot/vault_exporter#6]
I'm used to having `*_build_info` metrics, with labels like `build_time`, `version`, `revision`, and `goversion` for Go binaries. Not sure how possible all these labels are, though I do see that the `vault version` command can return the git commit... 🤔

**Comment by tomwilkie** [comment]
I think everything we can get from the API is exported in the `vault_info` metric, I believe `vault version` is actually telling you details about the `vault` binary you use as the CLI, and not the server: https://github.com/hashicorp/vault/blob/master/command/version.go#L55:23

**Comment by hairyhenderson** [comment]
@tomwilkie right - it's the vault CLI binary's info - sometimes that's one and the same as the server, but I suppose there's no guarantee.

I'll close this for now. Thanks for the comment!
